---
title: "Relatório_Viagens"
author: "Lucas Luiz"
date: "2023-04-07"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
summary(cars)
```

## 1 - Qual é o valor gasto por órgão em passagens?

```{r render(ggplot),echo = FALSE}
library(ggplot2)
ggplot(p1, aes(x = reorder(orgao, valor), y = valor))+
  geom_bar(stat = "identity")+
  coord_flip()+
  labs(x = "Valor", y = "Órgãos")

```

## 2 - Qual é o valor gasto por cidade?

```{r render(ggplot),echo = FALSE}
library(ggplot2)
ggplot(p2, aes(x = reorder(destino, valor), y = valor))+
  geom_bar(stat = "identity", fill = "#0ba791")+
  geom_text(aes(label = valor), vjust = 0.3, size = 3)+
  coord_flip()+
  labs(x = "Valor", y = "Destino")

```

## 3 - Qual é a quantidade de viagens por mês?

```{r render(ggplot),echo = FALSE}
library(ggplot2)
ggplot(p3,aes(x=data.inicio.formatada, y=qtd, group= 1))+
  geom_line()+
  geom_point()
```

```         
```

```         
```

```         
```
